apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Infra
      targetRevision: HEAD
      path: charts/registry
      helm:
        releaseName: registry
        valueFiles:
          - $values/prod/registry/values/registry-values.yaml
    - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Infra
      ref: values
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
