apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.grafana.route.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/target: {{ .Values.targetIP | quote }}
spec:
  parentRefs:
    {{- range .Values.grafana.route.sections }}
    - name: {{ $.Values.gateway.name }}
      namespace: {{ $.Values.gateway.namespace }}
      sectionName: {{ . }}
    {{- end }}
  hostnames:
    - {{ .Values.grafanaHostname }}
  rules:
    - backendRefs:
        - name: {{ .Values.grafana.backendService }}
          port: {{ .Values.grafana.backendPort }}
