targetIP: "178.104.84.100"
hostname: argocd-dev.easysolution.work

namespace: argocd

serverInsecure: true

gateway:
  name: main-gateway
  namespace: nginx-gateway

route:
  name: argocd-route
  sections: [http, https]
  backendService: argocd-server
  backendPort: 80

extraConfigMaps: {}
extraRoutes: []
