apiVersion: v1
kind: Service
metadata:
  name: easy-deploy-webhook
  namespace: easy-deploy-system
  labels:
    app.kubernetes.io/name: easy-deploy-operator
spec:
  selector:
    app.kubernetes.io/name: easy-deploy-operator
  ports:
    - name: webhook
      port: 9090
      targetPort: 9090
      protocol: TCP
