environment: prod
baseDomain: easysolution.work
targetIP: "116.203.203.121"
registryURL: registry.easysolution.work
webhookHostname: webhook.easysolution.work

operator:
  image: ghcr.io/murad-suleymanov/easy-deploy-operator:2eaa2b2d576529c782f46a14d527c20cb682c587
  replicas: 1
