crds:
  enabled: false

kubeControllerManager:
  enabled: true
kubeScheduler:
  enabled: true
kubeEtcd:
  enabled: true

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  serviceMonitor:
    enabled: true
  grafana.ini:
    metrics:
      enabled: true
  initChownData:
    enabled: false
  podSecurityContext:
    fsGroup: 472
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    runAsUser: 472
    runAsGroup: 472
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    retention: 7d
    additionalScrapeConfigs:
      - job_name: 'vault'
        scheme: https
        metrics_path: /v1/sys/metrics
        params:
          format: ['prometheus']
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ['vault.easysolution.work']
            labels:
              instance: vault
      - job_name: 'keycloak'
        scheme: https
        metrics_path: /metrics
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ['keycloak.easysolution.work']
            labels:
              instance: keycloak
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
