defaultVaultConnection:
  enabled: true
  address: https://vault.easysolution.work
  skipTLSVerify: false

defaultAuthMethod:
  enabled: true
  method: kubernetes
  mount: kubernetes-prod
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: vault-secrets-operator-controller-manager

controller:
  manager:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
