apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway/gateway.yaml
  - gateway/cluster-issuer.yaml
  - gateway/wildcard-certificate.yaml
  - gateway/reference-grants.yaml
  - gateway/grafana-route.yaml
  - gateway/registry-route.yaml
  - registry/namespace.yaml
  - registry/deployment.yaml
  - registry/service.yaml
  - operator/webhook-service.yaml
  - operator/webhook-route.yaml
  - monitoring/birservice-dashboard.yaml
