apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway/gateway.yaml
  - gateway/cluster-issuer.yaml
  - gateway/wildcard-certificate.yaml
  - gateway/reference-grants.yaml
  - gateway/grafana-route.yaml
  - gateway/registry-route.yaml
  - gateway/registry-ui-route.yaml
  - gateway/argocd-route.yaml
  - registry/namespace.yaml
  - registry/registry-auth-secret.yaml
  - registry/registry-ui-auth-secret.yaml
  - registry/deployment.yaml
  - registry/service.yaml
  - registry/registry-ui-deployment.yaml
  - registry/registry-ui-service.yaml
  - operator/webhook-service.yaml
  - operator/webhook-route.yaml
  - argocd/applicationset-birservices.yaml
  - argocd/server-insecure.yaml
  - monitoring/birservice-dashboard.yaml
  - monitoring/calico-servicemonitor.yaml
