apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Gateway core
  - gateway/gateway.yaml
  - gateway/cluster-issuer.yaml
  - gateway/wildcard-certificate.yaml
  - gateway/reference-grants.yaml

  # Registry
  - registry/namespace.yaml
  - registry/registry-auth-secret.yaml
  - registry/registry-ui-auth-secret.yaml
  - registry/deployment.yaml
  - registry/service.yaml
  - registry/registry-ui-deployment.yaml
  - registry/registry-ui-service.yaml
  - registry/registry-route.yaml
  - registry/registry-ui-route.yaml
  - registry/registry-client-settings.yaml

  # ArgoCD
  - argocd/applicationset-birservices.yaml
  - argocd/server-insecure.yaml
  - argocd/argocd-route.yaml
  - argocd/reference-grant.yaml

  # Monitoring
  - monitoring/birservice-dashboard.yaml
  - monitoring/calico-servicemonitor.yaml
  - monitoring/kube-proxy-servicemonitor.yaml
  - monitoring/operator-servicemonitor.yaml
  - monitoring/grafana-route.yaml
  - monitoring/reference-grant.yaml

  # Operator
  - operator/webhook-service.yaml
  - operator/webhook-route.yaml
