{{- range $key, $secret := .Values.secrets }}
{{- if $secret.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $key }}
  namespace: {{ $secret.namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ if $secret.fullPath }}{{ $secret.fullPath }}{{ else }}{{ $.Values.environment }}/{{ $secret.vaultPath }}{{ end }}
  destination:
    name: {{ $secret.name }}
    create: {{ $secret.create | default true }}
    overwrite: {{ $secret.overwrite | default true }}
  refreshAfter: {{ $secret.refreshInterval | default "1h" }}
  vaultAuthRef: vault-auth
{{- end }}
{{- end }}
