pilot:
  env:
    PILOT_ENABLE_AMBIENT: "true"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  traceSampling: 10.0

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultConfig:
    tracing:
      zipkin:
        address: otel-collector-opentelemetry-collector.observability.svc.cluster.local:9411
      sampling: 10.0
