pilot:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  traceSampling: 10.0

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultConfig:
    tracing:
      zipkin:
        address: jaeger-collector.istio-system:9411
      sampling: 10.0
