apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.wildcard.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  secretName: {{ .Values.wildcard.secretName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ printf "*.%s" .Values.baseDomain | quote }}
