namespace: observability

targetIP: "178.104.84.100"

gateway:
  name: main-gateway
  namespace: nginx-gateway

route:
  sections: [http, https]

minio:
  consoleHostname: minio.easysolution.work
  consoleService: minio-console
  consolePort: 9001
  apiHostname: s3.easysolution.work
  apiService: minio
  apiPort: 9000

instrumentation:
  name: default
  exporterEndpoint: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318
  samplingRatio: "0.1"
  propagators:
    - tracecontext
    - baggage
    - b3
  images:
    java: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    python: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
    nodejs: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    dotnet: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest
    go: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:latest
