apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.16.1
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/dev/dns/values/external-dns-values.yaml
    - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Infra
      ref: values
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
