targetIP: "116.203.203.121"
kialiHostname: kiali.easysolution.work
jaegerHostname: ""

gateway:
  name: main-gateway
  namespace: nginx-gateway

injectedNamespaces:
  - easy-deploy-system

meshConfig:
  mtlsMode: STRICT
  metricsExceptions:
    - name: easy-deploy-operator
      namespace: easy-deploy-system
      selector:
        app.kubernetes.io/name: easy-deploy-operator
      ports:
        - 8080
        - 8081
        - 9090

tracing:
  enabled: true
  samplingRate: 10

route:
  sections: [http, https]

oauth2Proxy:
  enabled: false
  issuerUrl: ""
  clientId: jaeger-proxy
