targetIP: "178.104.84.100"
kialiHostname: kiali-dev.easysolution.work
jaegerHostname: jaeger-dev.easysolution.work

gateway:
  name: main-gateway
  namespace: nginx-gateway

injectedNamespaces:
  - easy-deploy-system

meshConfig:
  mtlsMode: STRICT
  metricsExceptions:
    - name: easy-deploy-operator
      namespace: easy-deploy-system
      selector:
        app.kubernetes.io/name: easy-deploy-operator
      ports:
        - 8080
        - 8081

tracing:
  enabled: true
  samplingRate: 100

route:
  sections: [http, https]

oauth2Proxy:
  enabled: true
  issuerUrl: https://keycloak-dev.easysolution.work/realms/istio
  clientId: jaeger-proxy
