environment: dev
baseDomain: easysolution.work
targetIP: "178.104.84.100"
registryURL: registry-dev.easysolution.work
webhookHostname: webhook-dev.easysolution.work

operator:
  image: ghcr.io/murad-suleymanov/easy-deploy-operator:2eaa2b2d576529c782f46a14d527c20cb682c587
  replicas: 1
