apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-gateway-fabric
    repoURL: ghcr.io/nginx/charts
    targetRevision: 2.4.2
    helm:
      releaseName: ngf
      values: |
        nginx:
          container:
            hostPorts:
              - port: 80
                containerPort: 80
              - port: 443
                containerPort: 443
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
