apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: easy-deploy-birservices
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Murad-Suleymanov/BasePlate-Dev
        revision: HEAD
        files:
          - path: "tenants/*/simple-yaml/*.yaml"
  template:
    metadata:
      name: '{{ printf "%s-%s" (index (splitList "/" .path.path) 1) (trimSuffix ".yaml" .path.filenameNormalized) }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Murad-Suleymanov/BasePlate
          targetRevision: HEAD
          path: charts/birservice
          helm:
            releaseName: '{{ trimSuffix ".yaml" .path.filenameNormalized }}'
            valueFiles:
              - '$values/{{ .path.path }}/{{ .path.filename }}'

        - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Dev
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index (splitList "/" .path.path) 1 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
