environment: dev

vault:
  server: https://vault.easysolution.work
  authPath: kubernetes-dev
  role: vault-secrets-operator
  serviceAccount: vault-secrets-operator
  skipTLSVerify: false

secrets:
  grafana-admin:
    enabled: true
    name: grafana-admin-secret
    namespace: monitoring
    refreshInterval: 1h
    vaultPath: monitoring/grafana

  cloudflare-cert-manager:
    enabled: true
    name: cloudflare-api-token
    namespace: cert-manager
    refreshInterval: 1h
    vaultPath: cloudflare

  cloudflare-external-dns:
    enabled: true
    name: cloudflare-api-token
    namespace: external-dns
    refreshInterval: 1h
    vaultPath: cloudflare

  github-pipeline:
    enabled: true
    name: github-pipeline-secret
    namespace: easy-deploy-system
    refreshInterval: 1h
    vaultPath: github

  registry-auth:
    enabled: true
    name: registry-auth
    namespace: registry
    refreshInterval: 1h
    vaultPath: registry

  argocd-admin:
    enabled: true
    name: argocd-secret
    namespace: argocd
    refreshInterval: 1h
    vaultPath: argocd
    create: false
    overwrite: false
