targetIP: ""
kialiHostname: ""
jaegerHostname: ""

gateway:
  name: main-gateway
  namespace: nginx-gateway

injectedNamespaces:
  - easy-deploy-system

meshConfig:
  mtlsMode: STRICT
  permissivePorts: []

tracing:
  enabled: true
  samplingRate: 100

route:
  sections:
    - http
    - https

oauth2Proxy:
  enabled: false
  issuerUrl: ""
  clientId: jaeger-proxy
