apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: easy-deploy-birservices-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Murad-Suleymanov/BasePlate-Dev
        revision: HEAD
        files:
          - path: "*/dev.yaml"
  template:
    metadata:
      name: '{{ printf "%s-dev" .path.path }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Murad-Suleymanov/BasePlate
          targetRevision: HEAD
          path: charts/birservice
          helm:
            releaseName: '{{ .path.path }}'
            valueFiles:
              - '$values/{{ .path.path }}/{{ .path.filename }}'
        - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Dev
          targetRevision: HEAD
          ref: values
      destination:
        name: dev-cluster
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
