apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
              value: '["*"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
              value: '["HEAD","GET","OPTIONS","DELETE"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
              value: '["Authorization"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
              value: '["Docker-Content-Digest"]'
      volumes:
        - name: registry-data
          hostPath:
            path: /opt/registry-data
            type: DirectoryOrCreate
