apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: registry
spec:
  replicas: {{ .Values.registry.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
    spec:
      containers:
        - name: registry
          image: {{ .Values.registry.image }}
          ports:
            - containerPort: {{ .Values.registry.port }}
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
            - name: registry-auth
              mountPath: /auth
              readOnly: true
{{- range .Values.registry.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
{{- if .readOnly }}
              readOnly: {{ .readOnly }}
{{- end }}
{{- end }}
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
              value: '["https://{{ .Values.registryUIHostname }}"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials
              value: '["true"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
              value: '["HEAD","GET","OPTIONS","DELETE","POST","PUT"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
              value: '["Authorization","Accept","Cache-Control","Content-Type"]'
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
              value: '["Docker-Content-Digest"]'
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
{{- range .Values.registry.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
      volumes:
        - name: registry-data
          hostPath:
            path: {{ .Values.registry.storageHostPath }}
            type: DirectoryOrCreate
        - name: registry-auth
          secret:
            secretName: registry-auth
            items:
              - key: htpasswd
                path: htpasswd
{{- range .Values.registry.extraVolumes }}
        - name: {{ .name }}
{{- if .emptyDir }}
          emptyDir: {}
{{- end }}
{{- if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            type: {{ .hostPath.type | default "DirectoryOrCreate" }}
{{- end }}
{{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
{{- end }}
{{- end }}
