apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-gc-config
  namespace: {{ .Values.namespace }}
data:
  config.yml: |
    version: 0.1
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
