apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: registry-body-size
  namespace: registry
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: registry-route
  body:
    maxSize: "0"
    timeout: "300s"
