apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: registry-body-size
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: registry-route
  body:
    maxSize: {{ .Values.clientSettings.maxSize | quote }}
    timeout: {{ .Values.clientSettings.timeout | quote }}
