apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: registry
spec:
  type: {{ .Values.registry.service.type }}
  selector:
    app.kubernetes.io/name: registry
  ports:
    - port: {{ .Values.registry.port }}
      targetPort: {{ .Values.registry.port }}
      nodePort: {{ .Values.registry.service.nodePort }}
      protocol: TCP
