apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Infra
      targetRevision: HEAD
      path: charts/infra-applications
      helm:
        releaseName: infra-applications
        valueFiles:
          - $values/prod/infra-applications-values.yaml
    - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Infra
      ref: values
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
