# service_name/namespace_name.yaml — service_name altında bir neçə namespace (fayl) ola bilər
# Məs: hello-csharp/loadtest.yaml, hello-csharp/prod.yaml, api/dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: easy-deploy-birservices
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Murad-Suleymanov/BasePlate-Dev
        revision: HEAD
        files:
          - path: "*/*.yaml"
  template:
    metadata:
      name: '{{ printf "%s-%s" .path.path (trimSuffix ".yaml" .path.filename) }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Murad-Suleymanov/BasePlate
          targetRevision: HEAD
          path: charts/birservice
          helm:
            releaseName: '{{ .path.path }}'
            valueFiles:
              - '$values/{{ .path.path }}/{{ .path.filename }}'
        - repoURL: https://github.com/Murad-Suleymanov/BasePlate-Dev
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ trimSuffix ".yaml" .path.filename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
