istio_namespace: istio-system

auth:
  strategy: openid
  openid:
    client_id: kiali
    issuer_uri: https://keycloak.easysolution.work/realms/istio
    scopes: [openid, profile, email]
    username_claim: preferred_username
    disable_rbac: true

deployment:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  ingress:
    enabled: false

server:
  web_fqdn: kiali.easysolution.work
  web_port: 443
  web_schema: https

external_services:
  prometheus:
    url: http://monitoring-kube-prometheus-prometheus.monitoring:9090
  grafana:
    enabled: true
    in_cluster_url: http://monitoring-grafana.monitoring:80
    url: https://grafana.easysolution.work
  tracing:
    enabled: true
    provider: jaeger
    in_cluster_url: http://jaeger.istio-system:16686
    url: https://jaeger.easysolution.work
    use_grpc: false
