pilot:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  traceSampling: 100.0

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultConfig:
    tracing:
      zipkin:
        address: jaeger-collector.istio-system:9411
      sampling: 100.0
