pilot:
  env:
    PILOT_ENABLE_AMBIENT: "true"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  traceSampling: 100.0

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultConfig:
    tracing:
      zipkin:
        address: otel-collector.observability.svc.cluster.local:9411
      sampling: 100.0
