{{- if .Values.serviceMonitors.kubeProxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: kube-proxy-metrics
  namespace: kube-system
  labels:
    k8s-app: kube-proxy
spec:
  clusterIP: None
  ports:
    - port: 10249
      protocol: TCP
      name: metrics
  selector:
    k8s-app: kube-proxy
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  namespaceSelector:
    matchNames: [kube-system]
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.scrapeInterval }}
{{- end }}
