{{- if .Values.serviceMonitors.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.operator.labelName }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.labelName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.operator.labelName }}
  namespaceSelector:
    matchNames: [{{ .Values.operator.namespace }}]
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.scrapeInterval }}
{{- end }}
